// packages/frontend/src/components/FileExplorer.tsx
import { useState, useEffect, useRef } from 'react'
import { ChevronRight, RefreshCw, Home, FolderOpen } from 'lucide-react'
import { sandboxApi } from '../api/sandbox'
import { useChatStore } from '../stores/chat'
import FileTreeItem, { type FileNode } from './FileTreeItem'
import './FileExplorer.css'

interface FileExplorerProps {
  sessionId: string | null
  onSelectFile: (path: string) => void
}

export default function FileExplorer({ sessionId, onSelectFile }: FileExplorerProps) {
  // 每个属性单独订阅 - 最简单可靠的方式
  const isStreaming = useChatStore((state) => state.isStreaming)
  const filesChangedTrigger = useChatStore((state) => state.filesChangedTrigger)
  const sandboxReadySessionId = useChatStore((state) => state.sandboxReadySessionId)
  const isSwitchingSession = useChatStore((state) => state.isSwitchingSession)
  
  const [rootFiles, setRootFiles] = useState<FileNode[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [sandboxNotCreated, setSandboxNotCreated] = useState(false)
  const [currentSelectedPath, setCurrentSelectedPath] = useState<string | null>(null)
  const [expandedPaths, setExpandedPaths] = useState<Set<string>>(new Set())
  
  // Delete confirmation dialog
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<{ path: string; name: string } | null>(null)
  
  const previousSessionIdRef = useRef<string | null>(null)
  const wasStreamingRef = useRef(false)
  const activeSessionRef = useRef<string | null>(sessionId)

  useEffect(() => {
    activeSessionRef.current = sessionId
  }, [sessionId])

  // Helper functions
  const getFilesFingerprint = (files: FileNode[]): string => {
    const sortedFiles = [...files].sort((a, b) => a.path.localeCompare(b.path))
    return sortedFiles.map(f => `${f.path}|${f.type}|${f.size ?? 0}`).join(';')
  }

  const hasFilesChanged = (oldFiles: FileNode[], newFiles: { path: string; type: string; size?: number }[]): boolean => {
    if (oldFiles.length !== newFiles.length) return true
    
    const oldFingerprint = getFilesFingerprint(oldFiles)
    const newFingerprint = newFiles
      .sort((a, b) => a.path.localeCompare(b.path))
      .map(f => `${f.path}|${f.type}|${f.size ?? 0}`)
      .join(';')
    
    return oldFingerprint !== newFingerprint
  }

  const loadRootFiles = async (preserveExpanded = false) => {
    if (!sessionId || sandboxReadySessionId !== sessionId) return
    
    setIsLoading(true)
    setError(null)
    setSandboxNotCreated(false)
    
    try {
      const response = await sandboxApi.listFiles(sessionId, '/workspace')
      if (activeSessionRef.current !== sessionId) return
      
      setRootFiles(response.files.map(f => ({
        ...f,
        children: undefined,
        isOpen: preserveExpanded && expandedPaths.has(f.path),
        isLoading: false
      })) as FileNode[])
      
      setSandboxNotCreated(false)
    } catch (e: unknown) {
      const status = typeof e === 'object' && e !== null && 'status' in e
        ? (e as { status?: number }).status
        : undefined
      if (status === 404) {
        setSandboxNotCreated(true)
        setError(null)
        setRootFiles([])
      } else {
        setError(e instanceof Error ? e.message : 'Failed to load files')
        setRootFiles([])
      }
    } finally {
      setIsLoading(false)
    }
  }

  const loadFolderChildrenRecursive = async (node: FileNode, pathsToExpand: Set<string>) => {
    if (!sessionId || sandboxReadySessionId !== sessionId || node.type !== 'directory') return
    
    node.isLoading = true
    try {
      const response = await sandboxApi.listFiles(sessionId, node.path)
      if (activeSessionRef.current !== sessionId) return
      node.children = response.files.map(f => ({
        ...f,
        children: undefined,
        isOpen: pathsToExpand.has(f.path),
        isLoading: false
      })) as FileNode[]
      
      for (const child of node.children) {
        if (child.isOpen && child.type === 'directory') {
          loadFolderChildrenRecursive(child, pathsToExpand)
        }
      }
    } catch (e) {
      console.error('Failed to load folder:', e)
    } finally {
      node.isLoading = false
    }
  }

  const refreshWithExpandedState = async () => {
    if (!sessionId || sandboxReadySessionId !== sessionId) return
    
    try {
      const response = await sandboxApi.listFiles(sessionId, '/workspace')
      if (activeSessionRef.current !== sessionId) return
      
      const pathsToExpand = new Set(expandedPaths)
      const rootChanged = hasFilesChanged(rootFiles, response.files)
      if (!rootChanged && pathsToExpand.size === 0) {
        console.debug('[FileExplorer] No changes detected, skipping refresh')
        return
      }
      
      console.debug('[FileExplorer] Refreshing files...')
      
      setRootFiles(response.files.map(f => ({
        ...f,
        children: undefined,
        isOpen: pathsToExpand.has(f.path),
        isLoading: false
      })) as FileNode[])
      
      // Load children for expanded folders regardless of root change
      for (const file of response.files) {
        if (pathsToExpand.has(file.path) && file.type === 'directory') {
          loadFolderChildrenRecursive(
            {
              ...file,
              children: undefined,
              isOpen: true,
              isLoading: false,
            } as FileNode,
            pathsToExpand,
          )
        }
      }
    } catch (e) {
      console.error('[FileExplorer] Refresh error:', e)
    }
  }

  const loadFolderChildren = async (node: FileNode) => {
    if (!sessionId || sandboxReadySessionId !== sessionId || node.type !== 'directory') return
    
    node.isLoading = true
    try {
      const response = await sandboxApi.listFiles(sessionId, node.path)
      if (activeSessionRef.current !== sessionId) return
      node.children = response.files.map(f => ({
        ...f,
        children: undefined,
        isOpen: false,
        isLoading: false
      })) as FileNode[]
    } catch (e) {
      console.error('Failed to load folder:', e)
    } finally {
      node.isLoading = false
    }
  }

  const handleToggle = async (node: FileNode) => {
    if (node.isOpen) {
      node.isOpen = false
      setExpandedPaths(prev => {
        const newSet = new Set(prev)
        newSet.delete(node.path)
        return newSet
      })
      setRootFiles([...rootFiles])
      return
    }
    
    node.isOpen = true
    setExpandedPaths(prev => new Set(prev).add(node.path))
    
    if (!node.children) {
      await loadFolderChildren(node)
    }
    setRootFiles([...rootFiles])
  }

  const handleSelect = (path: string) => {
    setCurrentSelectedPath(path)
    onSelectFile(path)
  }

  const handleDownload = async (path: string) => {
    if (!sessionId) return

    try {
      const { blob, filename } = await sandboxApi.download(sessionId, path)
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = filename
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
    } catch (e) {
      console.error('Download failed:', e)
    }
  }

  const handleDeleteRequest = (path: string, name: string) => {
    setDeleteTarget({ path, name })
    setShowDeleteConfirm(true)
  }

  const confirmDelete = async () => {
    if (!sessionId || !deleteTarget) return
    
    try {
      await sandboxApi.deleteFile(sessionId, deleteTarget.path)
      setShowDeleteConfirm(false)
      setDeleteTarget(null)
      await loadRootFiles(true)
    } catch (e) {
      console.error('Failed to delete:', e)
    }
  }

  const cancelDelete = () => {
    setShowDeleteConfirm(false)
    setDeleteTarget(null)
  }

  // Watch for session changes
  useEffect(() => {
    const oldSessionId = previousSessionIdRef.current
    previousSessionIdRef.current = sessionId
    if (isSwitchingSession) return

    if (sessionId && sandboxReadySessionId === sessionId) {
      if (oldSessionId !== undefined && oldSessionId !== null) {
        loadRootFiles()
      } else {
        setSandboxNotCreated(true)
        setRootFiles([])
      }
    } else {
      setRootFiles([])
      setSandboxNotCreated(Boolean(sessionId))
      setError(null)
    }
    // We intentionally react only to session/stream flags; `loadRootFiles` is stable enough for this lifecycle hook.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId, sandboxReadySessionId, isSwitchingSession])

  // Auto-refresh when streaming completes
  useEffect(() => {
    const wasStreaming = wasStreamingRef.current
    wasStreamingRef.current = isStreaming

    if (wasStreaming && !isStreaming && sessionId && sandboxReadySessionId === sessionId) {
      setTimeout(() => {
        loadRootFiles()
      }, 500)
    }
    // Triggered by streaming/session changes only; do not re-run for internal helper identity changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isStreaming, sessionId, sandboxReadySessionId])

  // Refresh when files change (via event from backend)
  useEffect(() => {
    if (sessionId && sandboxReadySessionId === sessionId && filesChangedTrigger > 0) {
      refreshWithExpandedState()
    }
    // This effect is keyed by backend file-change signals and active session.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filesChangedTrigger, sessionId, sandboxReadySessionId])

  return (
    <div className="file-explorer">
      {/* Header */}
      <div className="file-explorer-header">
        <div className="file-explorer-breadcrumb">
          <Home size={14} />
          <ChevronRight size={12} className="file-explorer-breadcrumb-separator" />
          <span>workspace</span>
        </div>
        {sessionId && (
          <button
            onClick={() => loadRootFiles(true)}
            disabled={isLoading}
            className="file-explorer-btn"
            title="Refresh"
          >
            <RefreshCw size={14} className={isLoading ? 'animate-spin' : ''} />
          </button>
        )}
      </div>

      {/* Files List */}
      <div className="flex-1 overflow-y-auto ide-scrollbar">
        {/* Empty State */}
        {!sessionId && (
          <div className="file-explorer-empty">
            <div className="file-explorer-empty-icon">
              <FolderOpen size={48} />
            </div>
            <p className="file-explorer-empty-text">No active session<br />Start a chat to see files</p>
          </div>
        )}

        {/* Loading Root */}
        {sessionId && isLoading && rootFiles.length === 0 && (
          <div className="file-explorer-empty">
            <div className="w-6 h-6 rounded-full border-2 border-[var(--border-color)] border-t-[var(--accent)] animate-spin"></div>
            <p className="file-explorer-empty-text mt-3">Loading...</p>
          </div>
        )}

        {/* Sandbox Not Created */}
        {sandboxNotCreated && (
          <div className="file-explorer-empty">
            <div className="file-explorer-empty-icon">
              <FolderOpen size={48} />
            </div>
            <p className="file-explorer-empty-text">
              Workspace not ready<br />
              Run code with AI agent, or click refresh
            </p>
          </div>
        )}

        {/* Error */}
        {error && (
          <div className="file-explorer-empty">
            <div className="w-10 h-10 rounded-lg bg-[#ff3b30]/10 flex items-center justify-center mb-3">
              <svg className="w-5 h-5 text-[#ff3b30]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </div>
            <p className="text-sm font-medium text-[#ff3b30] mb-1">Failed to load</p>
            <p className="file-explorer-empty-text">{error}</p>
          </div>
        )}

        {/* File Tree */}
        {!error && !sandboxNotCreated && !isLoading && rootFiles.length > 0 && (
          <div className="py-0.5">
            {rootFiles.map(file => (
              <FileTreeItem
                key={file.path}
                file={file}
                selectedPath={currentSelectedPath}
                onToggle={handleToggle}
                onSelect={handleSelect}
                onDownload={handleDownload}
                onDelete={handleDeleteRequest}
              />
            ))}
          </div>
        )}

        {/* Empty Root */}
        {!error && !sandboxNotCreated && !isLoading && rootFiles.length === 0 && sessionId && (
          <div className="h-full flex flex-col items-center justify-center p-4 text-center">
            <FolderOpen size={32} className="text-[#606060] mb-2" />
            <p className="text-xs text-[#808080]">Empty directory</p>
            <p className="text-xs text-[#606060] mt-1">No files in /workspace</p>
          </div>
        )}
      </div>

      {/* Delete Confirmation Dialog */}
      {showDeleteConfirm && (
        <div className="delete-overlay" onClick={cancelDelete}>
          <div className="delete-dialog" onClick={(e) => e.stopPropagation()}>
            <div className="delete-title">Confirm Delete</div>
            <div className="delete-message">
              Are you sure you want to delete <span className="font-medium text-white">{deleteTarget?.name}</span>?
            </div>
            <div className="delete-actions">
              <button className="delete-btn delete-btn-cancel" onClick={cancelDelete}>
                Cancel
              </button>
              <button className="delete-btn delete-btn-confirm" onClick={confirmDelete}>
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// packages/frontend/src/components/FileExplorer.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { sandboxApi } from '../api/sandbox'
import { useChatStore } from '../stores/chat'
import { ChevronRight, RefreshCw, Home, FolderOpen } from 'lucide-vue-next'
import FileTreeItem, { type FileNode } from './FileTreeItem.vue'

const props = defineProps<{
  sessionId: string | null
}>()

const emit = defineEmits<{
  selectFile: [path: string]
}>()

// Delete confirmation dialog
const showDeleteConfirm = ref(false)
const deleteTarget = ref<{ path: string; name: string } | null>(null)

const chatStore = useChatStore()

const rootFiles = ref<FileNode[]>([])
const isLoading = ref(false)
const error = ref<string | null>(null)
const sandboxNotCreated = ref(false)
const currentSelectedPath = ref<string | null>(null)

// Track expanded folder paths to preserve state on refresh
const expandedPaths = ref<Set<string>>(new Set())

// Helper function to create a fingerprint of file list for comparison
function getFilesFingerprint(files: FileNode[]): string {
  const sortedFiles = [...files].sort((a, b) => a.path.localeCompare(b.path))
  return sortedFiles.map(f => `${f.path}|${f.type}|${f.size ?? 0}`).join(';')
}

// Check if files have changed (structure or size)
function hasFilesChanged(oldFiles: FileNode[], newFiles: { path: string; type: string; size?: number }[]): boolean {
  if (oldFiles.length !== newFiles.length) return true
  
  const oldFingerprint = getFilesFingerprint(oldFiles)
  const newFingerprint = newFiles
    .sort((a, b) => a.path.localeCompare(b.path))
    .map(f => `${f.path}|${f.type}|${f.size ?? 0}`)
    .join(';')
  
  return oldFingerprint !== newFingerprint
}

// Load files when session changes
watch(() => props.sessionId, async (newSessionId, oldSessionId) => {
  if (newSessionId) {
    if (oldSessionId !== undefined && oldSessionId !== null) {
      await loadRootFiles()
    } else {
      sandboxNotCreated.value = true
      rootFiles.value = []
    }
  } else {
    rootFiles.value = []
    sandboxNotCreated.value = false
    error.value = null
  }
}, { immediate: true })

// Auto-refresh root files when agent completes a task
watch(() => chatStore.isStreaming, async (streaming, wasStreaming) => {
  if (wasStreaming && !streaming && props.sessionId) {
    await new Promise(resolve => setTimeout(resolve, 500))
    await loadRootFiles() 
  }
})

// Refresh when sandbox files change (via event from backend)
// Skip initial trigger (value = 0)
watch(() => chatStore.filesChangedTrigger, async (newVal, oldVal) => {
  if (props.sessionId && oldVal !== undefined && newVal > 0) {
    await refreshWithExpandedState()
  }
})

async function loadRootFiles(preserveExpanded = false) {
  if (!props.sessionId) return
  
  isLoading.value = true
  error.value = null
  sandboxNotCreated.value = false
  
  try {
    const response = await sandboxApi.listFiles(props.sessionId, '/workspace')
    
    // Map files - set isOpen based on expandedPaths if preserving
    rootFiles.value = response.files.map(f => ({
      ...f,
      children: undefined,
      isOpen: preserveExpanded && expandedPaths.value.has(f.path),
      isLoading: false
    })) as FileNode[]
    
    sandboxNotCreated.value = false
  } catch (e: any) {
    if (e?.status === 404) {
      sandboxNotCreated.value = true
      error.value = null
      rootFiles.value = []
    } else {
      error.value = e instanceof Error ? e.message : 'Failed to load files'
      rootFiles.value = []
    }
  } finally {
    isLoading.value = false
  }
}

// Refresh and restore expanded folders (only if files changed)
async function refreshWithExpandedState() {
  if (!props.sessionId) return
  
  try {
    // Fetch new file list first
    const response = await sandboxApi.listFiles(props.sessionId, '/workspace')
    
    // Check if files have actually changed
    if (!hasFilesChanged(rootFiles.value, response.files)) {
      // No changes, skip refresh
      console.debug('[FileExplorer] No changes detected, skipping refresh')
      return
    }
    
    console.debug('[FileExplorer] Changes detected, refreshing...')
    
    // Save current expanded paths
    const pathsToExpand = new Set(expandedPaths.value)
    
    // Update root files with new data
    rootFiles.value = response.files.map(f => ({
      ...f,
      children: undefined,
      isOpen: pathsToExpand.has(f.path),
      isLoading: false
    })) as FileNode[]
    
    // Then load children for expanded folders (in background)
    for (const file of rootFiles.value) {
      if (file.isOpen && file.type === 'directory' && pathsToExpand.has(file.path)) {
        loadFolderChildrenRecursive(file, pathsToExpand)
      }
    }
  } catch (e) {
    console.error('[FileExplorer] Refresh error:', e)
  }
}

async function loadFolderChildrenRecursive(node: FileNode, pathsToExpand: Set<string>) {
  if (!props.sessionId || node.type !== 'directory') return
  
  node.isLoading = true
  try {
    const response = await sandboxApi.listFiles(props.sessionId, node.path)
    node.children = response.files.map(f => ({
      ...f,
      children: undefined,
      isOpen: pathsToExpand.has(f.path),
      isLoading: false
    })) as FileNode[]
    
    // Load expanded children (don't await, let them load in parallel)
    for (const child of node.children) {
      if (child.isOpen && child.type === 'directory') {
        loadFolderChildrenRecursive(child, pathsToExpand)
      }
    }
  } catch (e) {
    console.error('Failed to load folder:', e)
  } finally {
    node.isLoading = false
  }
}

async function loadFolderChildren(node: FileNode) {
  if (!props.sessionId || node.type !== 'directory') return
  
  node.isLoading = true
  try {
    const response = await sandboxApi.listFiles(props.sessionId, node.path)
    node.children = response.files.map(f => ({
      ...f,
      children: undefined,
      isOpen: false,
      isLoading: false
    })) as FileNode[]
  } catch (e) {
    console.error('Failed to load folder:', e)
  } finally {
    node.isLoading = false
  }
}

async function handleToggle(node: FileNode) {
  if (node.isOpen) {
    node.isOpen = false
    expandedPaths.value.delete(node.path)
    return
  }
  
  node.isOpen = true
  expandedPaths.value.add(node.path)
  
  if (!node.children) {
    await loadFolderChildren(node)
  }
}

function handleSelect(path: string) {
  currentSelectedPath.value = path
  emit('selectFile', path)
}

function handleDownload(path: string, _type: 'file' | 'directory') {
  if (!props.sessionId) return
  
  const url = sandboxApi.getDownloadUrl(props.sessionId, path)
  // Create a temporary link and click it to trigger download
  const link = document.createElement('a')
  link.href = url
  link.download = ''
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

function handleDeleteRequest(path: string, name: string) {
  deleteTarget.value = { path, name }
  showDeleteConfirm.value = true
}

async function confirmDelete() {
  if (!props.sessionId || !deleteTarget.value) return
  
  try {
    await sandboxApi.deleteFile(props.sessionId, deleteTarget.value.path)
    showDeleteConfirm.value = false
    deleteTarget.value = null
    // Refresh file list
    await loadRootFiles(true)
  } catch (e) {
    console.error('Failed to delete:', e)
  }
}

function cancelDelete() {
  showDeleteConfirm.value = false
  deleteTarget.value = null
}
</script>

<template>
  <div class="h-full flex flex-col bg-[#1e1e1e] select-none">
    <!-- Header - IDE Style -->
    <div class="h-9 flex items-center justify-between px-3 bg-[#252526] border-b border-[#3c3c3c]">
      <div class="flex items-center gap-1.5 text-xs text-[#cccccc]">
        <Home :size="12" class="text-[#75beff]" />
        <ChevronRight :size="10" class="text-[#808080]" />
        <span class="font-medium">workspace</span>
      </div>
      <button
        v-if="sessionId"
        @click="() => loadRootFiles(true)"
        :disabled="isLoading"
        class="p-1 hover:bg-[#3c3c3c] rounded transition-colors"
        title="Refresh"
      >
        <RefreshCw :size="12" :class="['text-[#808080] hover:text-[#cccccc]', { 'animate-spin': isLoading }]" />
      </button>
    </div>

    <!-- Files List -->
    <div class="flex-1 overflow-y-auto ide-scrollbar">
      <!-- Empty State -->
      <div v-if="!sessionId" class="h-full flex flex-col items-center justify-center p-4 text-center">
        <FolderOpen :size="32" class="text-[#606060] mb-2" />
        <p class="text-xs text-[#808080]">No active session</p>
        <p class="text-[10px] text-[#606060] mt-1">Start a chat to see files</p>
      </div>

      <!-- Loading Root -->
      <div v-else-if="isLoading && rootFiles.length === 0" class="h-full flex flex-col items-center justify-center p-4">
        <div class="w-6 h-6 rounded-full border border-[#606060] border-t-[#75beff] animate-spin"></div>
        <p class="text-[10px] text-[#808080] mt-2">Loading...</p>
      </div>

      <!-- Sandbox Not Created -->
      <div v-else-if="sandboxNotCreated" class="h-full flex flex-col items-center justify-center p-4 text-center">
        <FolderOpen :size="32" class="text-[#ccaa00] mb-2" />
        <p class="text-xs text-[#cccccc]">Workspace not ready</p>
        <p class="text-[10px] text-[#808080] mt-1 max-w-[140px]">
          Run code with AI agent, or click refresh
        </p>
      </div>

      <!-- Error -->
      <div v-else-if="error" class="h-full flex flex-col items-center justify-center p-4 text-center">
        <div class="w-8 h-8 rounded bg-[#5a1d1d] flex items-center justify-center mb-2">
          <svg class="w-4 h-4 text-[#f48771]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </div>
        <p class="text-xs text-[#f48771]">Failed to load</p>
        <p class="text-[10px] text-[#808080] mt-1">{{ error }}</p>
      </div>

      <!-- File Tree -->
      <div v-else-if="rootFiles.length > 0" class="py-0.5">
        <FileTreeItem
          v-for="file in rootFiles"
          :key="file.path"
          :file="file"
          :selected-path="currentSelectedPath"
          @toggle="handleToggle"
          @select="handleSelect"
          @download="handleDownload"
          @delete="handleDeleteRequest"
        />
      </div>

      <!-- Empty Root -->
      <div v-else class="h-full flex flex-col items-center justify-center p-4 text-center">
        <FolderOpen :size="32" class="text-[#606060] mb-2" />
        <p class="text-xs text-[#808080]">Empty directory</p>
        <p class="text-[10px] text-[#606060] mt-1">No files in /workspace</p>
      </div>
    </div>

    <!-- Delete Confirmation Dialog -->
    <Teleport to="body">
      <Transition name="fade">
        <div v-if="showDeleteConfirm" class="delete-overlay" @click.self="cancelDelete">
          <div class="delete-dialog">
            <div class="delete-title">Confirm Delete</div>
            <div class="delete-message">
              Are you sure you want to delete <span class="font-medium text-white">{{ deleteTarget?.name }}</span>?
            </div>
            <div class="delete-actions">
              <button class="delete-btn delete-btn-cancel" @click="cancelDelete">Cancel</button>
              <button class="delete-btn delete-btn-confirm" @click="confirmDelete">Delete</button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<style scoped>
.ide-scrollbar::-webkit-scrollbar {
  width: 10px;
}

.ide-scrollbar::-webkit-scrollbar-track {
  background: transparent;
}

.ide-scrollbar::-webkit-scrollbar-thumb {
  background: rgba(121, 121, 121, 0.4);
  border-radius: 0;
  border: 3px solid transparent;
  background-clip: padding-box;
}

.ide-scrollbar::-webkit-scrollbar-thumb:hover {
  background: rgba(121, 121, 121, 0.7);
  border: 3px solid transparent;
  background-clip: padding-box;
}

/* Delete confirmation dialog */
.delete-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
}

.delete-dialog {
  background: #252526;
  border: 1px solid #454545;
  border-radius: 8px;
  padding: 20px;
  min-width: 300px;
  max-width: 400px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.5);
}

.delete-title {
  font-size: 16px;
  font-weight: 600;
  color: #ffffff;
  margin-bottom: 12px;
}

.delete-message {
  font-size: 13px;
  color: #cccccc;
  margin-bottom: 20px;
  line-height: 1.5;
}

.delete-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}

.delete-btn {
  padding: 6px 16px;
  border-radius: 4px;
  font-size: 13px;
  cursor: pointer;
  transition: background 0.15s;
}

.delete-btn-cancel {
  background: transparent;
  border: 1px solid #454545;
  color: #cccccc;
}

.delete-btn-cancel:hover {
  background: #3c3c3c;
}

.delete-btn-confirm {
  background: #c53030;
  border: none;
  color: white;
}

.delete-btn-confirm:hover {
  background: #e53e3e;
}

/* Fade animation */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.15s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
